### ISSUE TITLE
Images in SFTP folders cant be opened

### ISSUE THREAD

**Issue by echza** [weclaw1/image-roll#36]
![resim](https://user-images.githubusercontent.com/879064/148592905-529bbc4f-1608-432b-93d3-b9d5d50b03c1.png)

Example folder name:          sftp://echza@192.168.1.3/var/www/

**Comment by weclaw1** [comment]
Do you use the newest version (1.4.0)? I fixed this in the latest release.

**Comment by echza** [comment]
Dear Robert problem still exist with the newest version 1.4.1

> Do you use the newest version (1.4.0 or 1.4.1)? I fixed this in the latest release.

**Comment by weclaw1** [comment]
You have most likely exceeded the limit of inotify watches.
Please run the following on the sftp server

`cat /proc/sys/fs/inotify/max_user_watches`

The command above should return the maximum number of inotify watches (for example 8096).
After that use the following command to make a temporary change of max watches (replace 16384 with the result of the previous command * 4 (so for 8096 please put in 32384):

`echo 16384 | sudo tee /proc/sys/fs/inotify/max_user_watches`

After that check if you still get the error, if everything is fixed use the following commands to set the limit permanently (again replace 16384 with the result of the first command * 4):

`echo fs.inotify.max_user_watches=16384 | sudo tee -a /etc/sysctl.conf`
`sudo sysctl -p`

If the problem still exists please let me know, I will make a debug build to get more logs.
